// <auto-generated />
using GcpBlog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GcpBlog.Domain.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("GcpBlog.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod diam quam, at dictum elit tincidunt in.",
                            Slug = "angular-11",
                            Title = "Angular 11"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Donec posuere iaculis iaculis. Donec pulvinar varius diam, nec tincidunt mauris cursus ut. Quisque fringilla risus dignissim justo ultricies aliquam.",
                            Slug = "core",
                            Title = ".NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Vestibulum egestas dapibus elit non facilisis. Maecenas sit amet elit sem. Donec eget placerat mauris. Sed sodales enim nec lacinia sagittis. Etiam at bibendum quam, condimentum commodo est.",
                            Slug = "git",
                            Title = "Git Hub"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
